#
# This Makefile is only for help - a wrapper around 'cargo build' to shorten the commands.
#
# Usage:
#	$ [DEFMT_LOG=trace|debug|info|...] [FEATURES=esp-hal-next|...] make -f Makefile.dev {m3|m3-with-espflash|m3-with-probe-rs|...}
#		# builds and runs a certain sample
#
DEFMT_LOG?=debug
FEATURES?=
LOG_ENV:=DEFMT_LOG=esp_hal=info,$(DEFMT_LOG)

DEFMT_HOST_FMT:='{t:dimmed} [{L:bold}] {s}'

REMAKE:=$(MAKE) -f $(MAKEFILE_LIST)

# Read the 'TARGET' from './cargo/config.toml'
#
TARGET:=$(shell cat .cargo/config.toml | grep -e '^target\s*=\s"' | cut -d '"' -f2)
	# riscv32imac-unknown-none-elf

ALL_FEATURES:=distance_mm

# Detect 'cargo' build cache
#
# NOTE: This is not very easy. Cargo only exposes the path (which can be defined in THREE different ways!) within
#		its own build system (as 'OUT_DIR' env.var.); there is no CLI way to ask for it.. Which is fine.
#
#		We have 'build.rs' write the path to '.OUT_DIR', from where we can pick it up, for running.
#
# YES: The author knows one can use Cargo runners. But this feels more free.
#
#	[1]: Cargo Book > Build cache
#		https://doc.rust-lang.org/stable/cargo/guide/build-cache.html
#
_OUT_DIR:=.OUT_DIR

# Note! Defined with '=' so that it gets re-evaluated on-site!
_OUT_EXAMPLE=$(shell cat ${_OUT_DIR} | sed -E 's^/build/.+$$^/examples/^')$(EXAMPLE)

all:
	@false

# Examples
#|m3:
#|	EXAMPLE=m3 \
#|	  FEATURES=targets_per_zone_2,distance_mm,reflectance_percent \
#|	  $(REMAKE) --no-print-directory _build _run

# Working solution for either C3/C6, preferring 'probe-rs' (if it works).
ifeq ($(TARGET),riscv32imc-unknown-none-elf)	# C3
m3-slim: m3-slim-with-espflash
else
m3-slim: m3-slim-with-probe
endif

m3-slim-with-espflash:
	EXAMPLE=m3 \
	  FEATURES=$(FEATURES),run_with_espflash,distance_mm \
	  $(REMAKE) --no-print-directory _build _run-with-espflash-v4

m3-slim-with-probe:
	EXAMPLE=m3 \
	  FEATURES=$(FEATURES),run_with_probe_rs,distance_mm \
	  $(REMAKE) --no-print-directory _build _run-with-probe-rs

#---
_build:
	$(LOG_ENV) cargo build --release --features=$(FEATURES) --example $(EXAMPLE)
	@test -f ${_OUT_DIR} || (echo >&2 "Did not generate ${_OUT_DIR}"; false)

_run-with-espflash:
	espflash flash --log-format defmt --monitor $(_OUT_EXAMPLE)

# Note: needs 'espflash' 4.0.0 (-dev)
_run-with-espflash-v4:
	espflash flash --log-format defmt --output-format $(DEFMT_HOST_FMT) --monitor $(_OUT_EXAMPLE)

_run-with-probe-rs:
	probe-rs run --log-format $(DEFMT_HOST_FMT) $(_OUT_EXAMPLE)

echo:
	@echo $(notdir $(_OUT_EXAMPLE))

.PHONY: all m3 _test _build _run echo
