#
# pins.toml
#
# Pins configuration for the project's examples. An include is generated, based on information in this file.
#
generate = "examples/pins_gen.in"

[boards.esp32c3]
SDA = 4
SCL = 5
PWR_EN = 6
INT=7

[boards.esp32c6]
SDA = 18
SCL = 19
PWR_EN = 21
INT = 22
