#
# References:
#   - Cargo Book > Configuration
#       -> https://doc.rust-lang.org/cargo/reference/config.html
#
[build]
target = "riscv32imc-unknown-none-elf"  # C3
#target = "riscv32imac-unknown-none-elf"  # C6

# Note: Cannot override the upper 'runner' just for tof's. Means we cannot use 'cargo run' within these subprojects.
#[target.'cfg(all())']
#runner = "espflash --log-format defmt --monitor"

rustflags = [
    "-C", "force-frame-pointers"
]
